package dev.heypr.yggdrasil.misc.discord.command.impl;

import dev.heypr.yggdrasil.Yggdrasil;
import dev.heypr.yggdrasil.misc.ColorManager;
import dev.heypr.yggdrasil.misc.discord.command.ISimpleCommand;
import dev.heypr.yggdrasil.misc.discord.command.Response;
import dev.heypr.yggdrasil.misc.discord.command.ResponseType;
import dev.heypr.yggdrasil.misc.discord.listeners.EventListener;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import org.bukkit.configuration.ConfigurationSection;

/**
 * Remove all roles created by this bot
 */
public final class DeleteRolesCommand implements ISimpleCommand {
    @Override
    public String name() {
        return "deleteroles";
    }

    @Override
    public String description() {
        return "Delete all roles generated by this bot.";
    }

    @Override
    public Response execute(final SlashCommandInteractionEvent e) {
        final Guild guild = e.getGuild();
        final ConfigurationSection rolesSection = EventListener.getRoles(guild.getId());

        if (rolesSection == null || rolesSection.getKeys(false).isEmpty())
            return Response.ResponseBuilder.response("No roles found.").setType(ResponseType.ERROR).build();

        int deleted = 0;

        for (final ColorManager.Colors colors : ColorManager.Colors.values()) {
            final String roleName = colors.getRoleName();
            final boolean exists = rolesSection.contains(roleName);

            if (!exists)
                continue;

            final String id = rolesSection.getString(roleName);
            final Role role = guild.getRoleById(id);

            if (role == null)
                continue;

            role.delete().queue();
            rolesSection.set(roleName, null);
            ++deleted;
        }

        Yggdrasil.plugin.saveConfig();

        return Response.ResponseBuilder.response(String.format("Successfully deleted `%s` roles.", deleted)).build();
    }

    @Override
    public boolean requireAdmin() {
        return true;
    }
}